#Secure Configuration Properties

##### SF Configuration #####

sf:
  username: "![ARM7usdD0Vlxvr3K0FTpqIRBLLsLwUpEqYsi4CWkMRbPernPyhmK4g==]"
  password: "![/D8WSZqYRkHBf4iIHvzK0g==]"
  token : "![awwgIto2M4mGiUB5Xj5ljtxMZn9YpKOE6/zxWFQQteA=]"
  authUrl : "![Yxlhgqf4mxjCoyJca+QfYsEl0PYUScEBHhwxwAHKdYwcBEaQ+v8dfrdnpXr0tng2nni/Sie3ORM=]"

##### SF Configuration #####